### ISSUE TITLE
Invalid constant value.dart(invalid_constant)

### ISSUE THREAD

**Issue by amreniouinnovent** [aloisdeniel/dio_retry#1]
I got Invalid constant value.dart(invalid_constant)
for the following line:

`      retryEvaluator: (error) => error.type != DioErrorType.CANCEL && error.type != DioErrorType.RESPONSE,`

How could I fix this error?

**Comment by peekpt** [comment]
@amreniouinnovent
removing all the "const"  fixed it for me
